In [7]:
import numpy as np

In [8]:

import numpy as np

print(np._version_,np.show_config)


AttributeError: module 'numpy' has no attribute '_version_'

In [9]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
n = np.zeros((5,5))
print("%d bytes" % (n.size * n.itemsize))

200 bytes


In [16]:
 import numpy as np
print(numpy.info(numpy.add))

NameError: name 'numpy' is not defined

In [19]:
x = np.zeros(10)
print(x)
#update the fifth value to 1
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [21]:
x=np.arange(10,49)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [24]:
x=np.arange(10,49)
print(x)
#reverse an array
x = x[::-1]
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [28]:
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
X =np.nonzero([1,2,0,0,4,0])

print(X)

(array([0, 1, 4], dtype=int64),)


In [40]:
x =np.arange(0,0,).reshape(3,3)
print(x)

ValueError: cannot reshape array of size 0 into shape (3,3)

In [49]:
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
 = np.random.random((3,3,3))
print(x)x

[[[0.19101321 0.22782126 0.49715771]
  [0.45804981 0.20619975 0.8854083 ]
  [0.4965351  0.11353255 0.82405707]]

 [[0.63040605 0.93652241 0.58851677]
  [0.63893465 0.67503104 0.84574587]
  [0.28113789 0.50269161 0.12663654]]

 [[0.96913442 0.03823414 0.86277436]
  [0.39659455 0.96601127 0.20799154]
  [0.1116216  0.29159258 0.20294505]]]


In [54]:
 x = np.random.random((10,10))
print(x)
#print minimun and maximum values
xmin,xmax = x.min(), x.max()
print(xmin,xmax)

[[0.98813092 0.91702163 0.96385002 0.94117691 0.46707727 0.85299361
  0.52063886 0.11593765 0.5598417  0.62283804]
 [0.03405061 0.44614965 0.81254004 0.95551481 0.9355329  0.05269822
  0.06298403 0.84346174 0.40872538 0.92497411]
 [0.90196967 0.81234999 0.43321796 0.83078288 0.38242668 0.03322867
  0.91923782 0.47337251 0.05967048 0.21670829]
 [0.98678982 0.86802921 0.69035027 0.6180668  0.23256167 0.84820856
  0.80480023 0.6456337  0.35906899 0.89634066]
 [0.56906396 0.62487959 0.16278122 0.9359867  0.24498432 0.57756236
  0.46758251 0.3012523  0.17154892 0.04854928]
 [0.85566926 0.58468781 0.10894716 0.64175144 0.28376474 0.73588863
  0.83083904 0.54801728 0.21506793 0.81295422]
 [0.01830825 0.11306603 0.03184238 0.87812598 0.08223844 0.94278917
  0.0751632  0.63913686 0.31429984 0.47328134]
 [0.97388712 0.3200908  0.03285595 0.12478708 0.93280975 0.43864747
  0.9403833  0.39767049 0.14970785 0.75384775]
 [0.3315358  0.82433876 0.72096481 0.64409375 0.20608851 0.47085558
  0.28383792

In [55]:
x = np.random.random(30)
y = x.mean()
print(y)

0.48697262894526366


In [57]:
x = np.ones((5,5))
print(x)
#put 1 on the border while 0 is inside
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [67]:
x = np.ones((3,3))
print(x)

#borders with zeros
x = np.pad(x,pad_width=1,mode="constant", constant_values=0)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [68]:
print (0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print (np.nan - np.nan)
print (np.nan in set([np.nan]))
print (0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [76]:
x = np.diag([1,2,3,4,5],k = -1)

print(x)

[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]]


In [77]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
